# Generated by Django 5.1.1 on 2024-09-06 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('phone_number', models.CharField(max_length=30, verbose_name='Номер телефона')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Завод',
                'verbose_name_plural': 'Завода',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('model', models.CharField(max_length=200, verbose_name='Модель')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('release_date', models.DateField(verbose_name='Дата выхода на рынок')),
                ('arrears', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Задолженность')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.factory', verbose_name='Завод')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('phone_number', models.CharField(max_length=30, verbose_name='Номер телефона')),
                ('arrears', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Задолженность')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.factory', verbose_name='Завод')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Индивидуальное предприятие',
                'verbose_name_plural': 'Индивидуальные предприятия',
            },
        ),
        migrations.CreateModel(
            name='Retail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('phone_number', models.CharField(max_length=30, verbose_name='Номер телефона')),
                ('arrears', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Задолженность')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.factory', verbose_name='Завод')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Розничный магазин',
                'verbose_name_plural': 'Розничные магазины',
            },
        ),
    ]
