# Generated by Django 5.1.1 on 2024-09-08 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factory',
            options={'verbose_name': 'Завод', 'verbose_name_plural': 'Заводы'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='arrears',
        ),
    ]
